exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = nm-applet
exec-once = waybar
exec-once = hyprpaper
#systemd esta a correr o hypridle, descomentar se aalterar
#exec-once = hypridle
exec-once = swaync
exec-once = /usr/bin/simplepolkitagent
exec-once = udiskie --notify
