# Main config

source = ~/.config/dotfiles/hypr/autostart.conf
source = ~/.config/dotfiles/hypr/lookandfeel.conf
source = ~/.config/dotfiles/hypr/input.conf
source = ~/.config/dotfiles/hypr/misc.conf
source = ~/.config/dotfiles/hypr/keybinds.conf
source = ~/.config/dotfiles/hypr/windowworkspaces.conf
#source = ~/.config/dotfiles/hypr/hypridle.conf
