input {
    kb_layout = es

    follow_mouse = 1

    sensitivity = 0

    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -1
}



#######################
#######Monitor#########
#######################

monitor=eDP-1,1920x1080@60,0x0,1.25
