###################
### MY PROGRAMS ###
###################

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = wofi
$browser = firefox

###################
### KEYBINDINGS ###
###################

bind = SUPER, T, exec,$terminal
bind = SUPER, SPACE, exec, pkill wofi || wofi --show drun
bind = SUPER, B, exec, $browser
bind = SUPER, W, killactive,
bind = SUPER, O, exec, obsidian
bind = SUPER, E, exec, $fileManager
bind = SUPER, F, togglefloating,
bind = SUPER, L, exec, hyprlock --config ~/.config/dotfiles/hypr/hyprlock/hyprlock.conf

#Fecha o Hyprland
bind = SUPER SHIFT, Q, exec, sh -c 'command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit'

#Iniciar e fechar a waybar
bind = SUPER, Escape, exec, killall waybar || waybar

#layout master
bind = SUPER, M, layoutmsg, swapwithmaster


# Move focus with mainMod + arrow keys
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
bind = SUPER, Tab, cyclenext,
# Switch workspaces with mainMod + [0-9]
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = SUPER, S, togglespecialworkspace, magic
bind = SUPER SHIFT, S, movetoworkspace, special:magic
# Scroll through existing workspaces with mainMod + scroll
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness etc

# Fn + F1: Mudar o estado do volume (mutar/desmutar)
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Fn + F2: Diminuir o volume
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

# Fn + F3: Aumentar o volume
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+

# Fn + F4: Mudar o estado do microfone (mutar/desmutar)
bind = , XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Fn + F5: Diminuir o brilho da tela
bind = , XF86MonBrightnessDown, exec, brightnessctl set 10%-

# Fn + F6: Aumentar o brilho da tela
bind = , XF86MonBrightnessUp, exec, brightnessctl set +10%

# Fn + F7: Ativar/Desativar projeção de tela (modo de tela externa)
bind = , XF86Display, exec, autorandr --toggle

# Fn + F8: Ativar/Desativar o modo de tela cheia (exemplo para alternar entre aplicações)
bind = , XF86AudioPlay, exec, wmctrl -r :ACTIVE: -b toggle,fullscreen

# Fn + F9: Ativar/desativar o modo avião
bind = , XF86AirplaneMode, exec, rfkill toggle all

# Fn + F10: Desativar/Ativar o touchpad
bind = , XF86TouchpadToggle, exec, synclient TouchpadOff=$(synclient -l | grep -c 'TouchpadOff.*=.*1')
