#!/bin/bash

quotes=(
"So sei que nada sei."
"Conhece-te a ti mesmo."
"O homem e a medida de todas as coisas."
"Nao sao as coisas que nos perturbam, mas a opiniao que temos delas."
"A felicidade da tua vida depende da qualidade dos teus pensamentos."
"Sofremos mais na imaginacao do que na realidade."
"Torna-te quem tu es."
"A vida nao tem sentido a priori, cabe-te dar-lhe um."
"No meio do inverno, aprendi finalmente que havia em mim um verao invencivel."
"Penso, logo existo."
"A simplicidade e a ultima sofisticao."
"A duvida e o principio da sabedoria."
"Se a mudanca que queres ver no mundo."
"A vida e realmente simples, mas insistimos em torna-la complicada."
"Quem tem um porquê enfrenta qualquer como."
"Aquele que conquista a si mesmo e o mais poderoso guerreiro."
"A persistencia realiza o impossivel."
"A felicidade nao e algo pronto, ela vem das tuas proprias acoes."
"O segredo da mudanca e focar toda a energia nao em lutar contra o velho, mas em construir o novo."
"Quem olha para fora sonha, quem olha para dentro desperta."
"A vida encolhe ou expande na proporcao da tua coragem."
"Nao e o que te acontece, mas como reages que importa."
"Grandes coisas nunca vem da zona de conforto."
"A mente e tudo. Aquilo que pensas, tornas-te."
"A disciplina e a ponte entre objetivos e realizacao."
"O obstaculo e o caminho."
"A melhor maneira de prever o futuro e cria-lo."
"Age como se aquilo que fazes fizesse diferenca. Porque faz."
"O homem que move montanhas comeca carregando pequenas pedras."
"A verdadeira sabedoria esta em reconhecer a propria ignorancia."
"Nao contes os dias, faz com que os dias contem."
"O silencio e uma fonte de grande forca."
"Aquilo que controlas define-te; aquilo que nao controlas ensina-te."
"Coragem nao e ausencia de medo, mas agir apesar dele."
"O sucesso e a soma de pequenos esforcos repetidos diariamente."
)

# Escolhe frase aleatória
echo "${quotes[$RANDOM % ${#quotes[@]}]}"
